spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create # DB 테이블 자동생성

server:
  port: 8080
